using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using SL.Domain.Models;

namespace SL.DisbursementService.Services
{
    public interface IDisbursementBatchRepository
    {
        Task<DisbursementBatch> GetDisbursementBatch();
    }

    public class DisbursementBatchRepository : IDisbursementBatchRepository
    {

        string dataJson = @"[
  {
    ""stageid"": """",
    ""traversedpath"": """",
    ""sl_adjustedpaymentcount"": ""0"",
    ""sl_adjustedpaymentcount_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_adjustedpaymentcount_state"": ""1"",
    ""sl_adjustedtotal_base"": ""0"",
    ""sl_adjustedtotal"": ""0"",
    ""sl_adjustedtotal_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_adjustedtotal_state"": ""1"",
    ""sl_approvaldate"": """",
    ""sl_name"": ""FDA20210216"",
    ""sl_workflowstatus"": """",
    ""sl_calrequisitionnumber"": """",
    ""sl_calresponsefilestatus"": ""Not Processed"",
    ""sl_calsubbatchstatus"": ""Undefer"",
    ""sl_csgprequisitionnumber"": """",
    ""sl_csgpresponsefilestatus"": ""Not Processed"",
    ""sl_cslsubbatchstatus"": """",
    ""sl_dlrequisitionnumber"": """",
    ""sl_dlresponsefilestatus"": ""Not Processed"",
    ""exchangerate"": ""1"",
    ""sl_faa33approvalemail"": """",
    ""sl_faa33approvalon"": """",
    ""sl_faa33approval"": """",
    ""sl_faa34apprvaldone"": ""Yes"",
    ""sl_faa34approvalon"": ""4/5/2021 1:00:00 PM"",
    ""sl_fdabatchid"": ""051b2e46-bad2-443a-9acc-c456423fa947"",
    ""sl_fiscalmonth"": """",
    ""sl_fiscalyear"": """",
    ""importsequencenumber"": """",
    ""sl_originaltotal_base"": """",
    ""sl_originaltotal"": """",
    ""sl_paymentcountrollup"": ""0"",
    ""sl_paymentcountrollup_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_paymentcountrollup_state"": ""1"",
    ""sl_preapprovaldone"": """",
    ""sl_preliminaryapprovedon"": ""4/21/2021 5:06:44 PM"",
    ""processid"": """",
    ""statecode"": ""Active"",
    ""statuscode"": ""Active"",
    ""sl_subbatchdeferalreason"": """",
    ""timezoneruleversionnumber"": ""0"",
    ""sl_originaltotalamount"": ""0"",
    ""sl_originaltotalamount_base"": ""0"",
    ""sl_originaltotalamount_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_originaltotalamount_state"": ""1"",
    ""utcconversiontimezonecode"": ""35"",
    ""versionnumber"": ""5796295"",
    ""transactioncurrencyid"": ""b1c907f7-1679-eb11-b1ab-0022486d7e62"",
    ""organizationid"": ""4172e8c8-b481-482b-a17b-beb6211a9163"",
    ""sl_batchfaa34approver.azureactivedirectoryobjectid"": """",
    ""createdonbehalfby.azureactivedirectoryobjectid"": """",
    ""createdby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_faa33approvalnotedby.azureactivedirectoryobjectid"": """",
    ""sl_faa34approver.azureactivedirectoryobjectid"": """",
    ""modifiedonbehalfby.azureactivedirectoryobjectid"": """",
    ""modifiedby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_preliminaryapprover.azureactivedirectoryobjectid"": """"
  },
  {
    ""stageid"": """",
    ""traversedpath"": """",
    ""sl_adjustedpaymentcount"": ""0"",
    ""sl_adjustedpaymentcount_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_adjustedpaymentcount_state"": ""1"",
    ""sl_adjustedtotal_base"": ""0"",
    ""sl_adjustedtotal"": ""0"",
    ""sl_adjustedtotal_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_adjustedtotal_state"": ""1"",
    ""sl_approvaldate"": """",
    ""sl_name"": ""FDA20210419"",
    ""sl_workflowstatus"": ""Workflow Ended"",
    ""sl_calrequisitionnumber"": ""014746221010041"",
    ""sl_calresponsefilestatus"": ""Not Processed"",
    ""sl_calsubbatchstatus"": ""Undefer"",
    ""sl_csgprequisitionnumber"": ""014746221010040"",
    ""sl_csgpresponsefilestatus"": ""Not Processed"",
    ""sl_cslsubbatchstatus"": ""Undefer"",
    ""sl_dlrequisitionnumber"": ""014746221010039"",
    ""sl_dlresponsefilestatus"": ""Not Processed"",
    ""exchangerate"": ""1"",
    ""sl_faa33approvalemail"": """",
    ""sl_faa33approvalon"": """",
    ""sl_faa33approval"": """",
    ""sl_faa34apprvaldone"": """",
    ""sl_faa34approvalon"": """",
    ""sl_fdabatchid"": ""9e46a788-1a57-408b-afe4-7c2b1e1cd062"",
    ""sl_fiscalmonth"": """",
    ""sl_fiscalyear"": """",
    ""importsequencenumber"": """",
    ""sl_originaltotal_base"": """",
    ""sl_originaltotal"": """",
    ""sl_paymentcountrollup"": ""27"",
    ""sl_paymentcountrollup_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_paymentcountrollup_state"": ""1"",
    ""sl_preapprovaldone"": """",
    ""sl_preliminaryapprovedon"": ""4/23/2021 5:37:30 PM"",
    ""processid"": """",
    ""statecode"": ""Active"",
    ""statuscode"": ""Active"",
    ""sl_subbatchdeferalreason"": """",
    ""timezoneruleversionnumber"": ""0"",
    ""sl_originaltotalamount"": ""89304"",
    ""sl_originaltotalamount_base"": ""89304"",
    ""sl_originaltotalamount_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_originaltotalamount_state"": ""1"",
    ""utcconversiontimezonecode"": ""35"",
    ""versionnumber"": ""5796290"",
    ""transactioncurrencyid"": ""b1c907f7-1679-eb11-b1ab-0022486d7e62"",
    ""organizationid"": ""4172e8c8-b481-482b-a17b-beb6211a9163"",
    ""sl_batchfaa34approver.azureactivedirectoryobjectid"": """",
    ""createdonbehalfby.azureactivedirectoryobjectid"": """",
    ""createdby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_faa33approvalnotedby.azureactivedirectoryobjectid"": """",
    ""sl_faa34approver.azureactivedirectoryobjectid"": """",
    ""modifiedonbehalfby.azureactivedirectoryobjectid"": """",
    ""modifiedby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_preliminaryapprover.azureactivedirectoryobjectid"": """"
  },
  {
    ""stageid"": """",
    ""traversedpath"": """",
    ""sl_adjustedpaymentcount"": ""0"",
    ""sl_adjustedpaymentcount_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_adjustedpaymentcount_state"": ""1"",
    ""sl_adjustedtotal_base"": ""0"",
    ""sl_adjustedtotal"": ""0"",
    ""sl_adjustedtotal_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_adjustedtotal_state"": ""1"",
    ""sl_approvaldate"": """",
    ""sl_name"": ""FDA20210413"",
    ""sl_workflowstatus"": """",
    ""sl_calrequisitionnumber"": """",
    ""sl_calresponsefilestatus"": ""Not Processed"",
    ""sl_calsubbatchstatus"": """",
    ""sl_csgprequisitionnumber"": """",
    ""sl_csgpresponsefilestatus"": ""Not Processed"",
    ""sl_cslsubbatchstatus"": """",
    ""sl_dlrequisitionnumber"": """",
    ""sl_dlresponsefilestatus"": ""Not Processed"",
    ""exchangerate"": ""1"",
    ""sl_faa33approvalemail"": """",
    ""sl_faa33approvalon"": """",
    ""sl_faa33approval"": """",
    ""sl_faa34apprvaldone"": """",
    ""sl_faa34approvalon"": """",
    ""sl_fdabatchid"": ""2bafced5-f27c-4c46-a425-6fe365f63b21"",
    ""sl_fiscalmonth"": """",
    ""sl_fiscalyear"": """",
    ""importsequencenumber"": """",
    ""sl_originaltotal_base"": """",
    ""sl_originaltotal"": """",
    ""sl_paymentcountrollup"": ""0"",
    ""sl_paymentcountrollup_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_paymentcountrollup_state"": ""1"",
    ""sl_preapprovaldone"": """",
    ""sl_preliminaryapprovedon"": """",
    ""processid"": """",
    ""statecode"": ""Active"",
    ""statuscode"": ""Active"",
    ""sl_subbatchdeferalreason"": """",
    ""timezoneruleversionnumber"": """",
    ""sl_originaltotalamount"": ""0"",
    ""sl_originaltotalamount_base"": ""0"",
    ""sl_originaltotalamount_date"": ""5/7/2021 5:13:16 PM"",
    ""sl_originaltotalamount_state"": ""1"",
    ""utcconversiontimezonecode"": """",
    ""versionnumber"": ""5796289"",
    ""transactioncurrencyid"": ""b1c907f7-1679-eb11-b1ab-0022486d7e62"",
    ""organizationid"": ""4172e8c8-b481-482b-a17b-beb6211a9163"",
    ""sl_batchfaa34approver.azureactivedirectoryobjectid"": """",
    ""createdonbehalfby.azureactivedirectoryobjectid"": """",
    ""createdby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_faa33approvalnotedby.azureactivedirectoryobjectid"": """",
    ""sl_faa34approver.azureactivedirectoryobjectid"": """",
    ""modifiedonbehalfby.azureactivedirectoryobjectid"": """",
    ""modifiedby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_preliminaryapprover.azureactivedirectoryobjectid"": """"
  },
  {
    ""stageid"": """",
    ""traversedpath"": """",
    ""sl_adjustedpaymentcount"": ""0"",
    ""sl_adjustedpaymentcount_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_adjustedpaymentcount_state"": ""1"",
    ""sl_adjustedtotal_base"": ""0"",
    ""sl_adjustedtotal"": ""0"",
    ""sl_adjustedtotal_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_adjustedtotal_state"": ""1"",
    ""sl_approvaldate"": """",
    ""sl_name"": ""FDA20210216"",
    ""sl_workflowstatus"": ""Response File Processed"",
    ""sl_calrequisitionnumber"": ""014746220120003"",
    ""sl_calresponsefilestatus"": ""Processed"",
    ""sl_calsubbatchstatus"": ""Undefer"",
    ""sl_csgprequisitionnumber"": ""014746220120002"",
    ""sl_csgpresponsefilestatus"": ""Processed"",
    ""sl_cslsubbatchstatus"": ""Defer"",
    ""sl_dlrequisitionnumber"": ""014746220120001"",
    ""sl_dlresponsefilestatus"": ""Processed"",
    ""exchangerate"": ""1"",
    ""sl_faa33approvalemail"": """",
    ""sl_faa33approvalon"": ""4/13/2021 2:10:38 PM"",
    ""sl_faa33approval"": ""Approved"",
    ""sl_faa34apprvaldone"": ""Yes"",
    ""sl_faa34approvalon"": ""4/5/2021 1:00:00 PM"",
    ""sl_fdabatchid"": ""9e0ab349-5d8b-4ff8-9f48-9384493c58e5"",
    ""sl_fiscalmonth"": """",
    ""sl_fiscalyear"": """",
    ""importsequencenumber"": """",
    ""sl_originaltotal_base"": """",
    ""sl_originaltotal"": """",
    ""sl_paymentcountrollup"": ""628"",
    ""sl_paymentcountrollup_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_paymentcountrollup_state"": ""1"",
    ""sl_preapprovaldone"": """",
    ""sl_preliminaryapprovedon"": ""4/29/2021 4:43:32 PM"",
    ""processid"": """",
    ""statecode"": ""Active"",
    ""statuscode"": ""Active"",
    ""sl_subbatchdeferalreason"": ""System Outage"",
    ""timezoneruleversionnumber"": ""0"",
    ""sl_originaltotalamount"": ""4286525.07"",
    ""sl_originaltotalamount_base"": ""4286525.07"",
    ""sl_originaltotalamount_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_originaltotalamount_state"": ""1"",
    ""utcconversiontimezonecode"": ""35"",
    ""versionnumber"": ""5796284"",
    ""transactioncurrencyid"": ""b1c907f7-1679-eb11-b1ab-0022486d7e62"",
    ""organizationid"": ""4172e8c8-b481-482b-a17b-beb6211a9163"",
    ""sl_batchfaa34approver.azureactivedirectoryobjectid"": """",
    ""createdonbehalfby.azureactivedirectoryobjectid"": """",
    ""createdby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_faa33approvalnotedby.azureactivedirectoryobjectid"": """",
    ""sl_faa34approver.azureactivedirectoryobjectid"": """",
    ""modifiedonbehalfby.azureactivedirectoryobjectid"": """",
    ""modifiedby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_preliminaryapprover.azureactivedirectoryobjectid"": """"
  },
  {
    ""stageid"": """",
    ""traversedpath"": """",
    ""sl_adjustedpaymentcount"": ""0"",
    ""sl_adjustedpaymentcount_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_adjustedpaymentcount_state"": ""1"",
    ""sl_adjustedtotal_base"": ""0"",
    ""sl_adjustedtotal"": ""0"",
    ""sl_adjustedtotal_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_adjustedtotal_state"": ""1"",
    ""sl_approvaldate"": """",
    ""sl_name"": ""FDA20210413"",
    ""sl_workflowstatus"": ""Workflow Ended"",
    ""sl_calrequisitionnumber"": """",
    ""sl_calresponsefilestatus"": ""Not Processed"",
    ""sl_calsubbatchstatus"": ""Defer"",
    ""sl_csgprequisitionnumber"": """",
    ""sl_csgpresponsefilestatus"": ""Not Processed"",
    ""sl_cslsubbatchstatus"": """",
    ""sl_dlrequisitionnumber"": """",
    ""sl_dlresponsefilestatus"": ""Not Processed"",
    ""exchangerate"": ""1"",
    ""sl_faa33approvalemail"": """",
    ""sl_faa33approvalon"": """",
    ""sl_faa33approval"": """",
    ""sl_faa34apprvaldone"": """",
    ""sl_faa34approvalon"": """",
    ""sl_fdabatchid"": ""da1f9410-b7c3-4aae-bac1-4d0cfd818d19"",
    ""sl_fiscalmonth"": """",
    ""sl_fiscalyear"": """",
    ""importsequencenumber"": """",
    ""sl_originaltotal_base"": """",
    ""sl_originaltotal"": """",
    ""sl_paymentcountrollup"": ""11"",
    ""sl_paymentcountrollup_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_paymentcountrollup_state"": ""1"",
    ""sl_preapprovaldone"": """",
    ""sl_preliminaryapprovedon"": """",
    ""processid"": """",
    ""statecode"": ""Active"",
    ""statuscode"": ""Active"",
    ""sl_subbatchdeferalreason"": ""Administrative Discretion"",
    ""timezoneruleversionnumber"": """",
    ""sl_originaltotalamount"": ""39355.66"",
    ""sl_originaltotalamount_base"": ""39355.66"",
    ""sl_originaltotalamount_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_originaltotalamount_state"": ""1"",
    ""utcconversiontimezonecode"": """",
    ""versionnumber"": ""5796283"",
    ""transactioncurrencyid"": ""b1c907f7-1679-eb11-b1ab-0022486d7e62"",
    ""organizationid"": ""4172e8c8-b481-482b-a17b-beb6211a9163"",
    ""sl_batchfaa34approver.azureactivedirectoryobjectid"": """",
    ""createdonbehalfby.azureactivedirectoryobjectid"": """",
    ""createdby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_faa33approvalnotedby.azureactivedirectoryobjectid"": """",
    ""sl_faa34approver.azureactivedirectoryobjectid"": """",
    ""modifiedonbehalfby.azureactivedirectoryobjectid"": """",
    ""modifiedby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_preliminaryapprover.azureactivedirectoryobjectid"": """"
  },
  {
    ""stageid"": """",
    ""traversedpath"": """",
    ""sl_adjustedpaymentcount"": ""0"",
    ""sl_adjustedpaymentcount_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_adjustedpaymentcount_state"": ""1"",
    ""sl_adjustedtotal_base"": ""0"",
    ""sl_adjustedtotal"": ""0"",
    ""sl_adjustedtotal_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_adjustedtotal_state"": ""1"",
    ""sl_approvaldate"": """",
    ""sl_name"": ""FDA20210412"",
    ""sl_workflowstatus"": """",
    ""sl_calrequisitionnumber"": """",
    ""sl_calresponsefilestatus"": ""Not Processed"",
    ""sl_calsubbatchstatus"": ""Defer"",
    ""sl_csgprequisitionnumber"": ""014746221010004"",
    ""sl_csgpresponsefilestatus"": ""Not Processed"",
    ""sl_cslsubbatchstatus"": """",
    ""sl_dlrequisitionnumber"": ""014746221010003"",
    ""sl_dlresponsefilestatus"": ""Not Processed"",
    ""exchangerate"": ""1"",
    ""sl_faa33approvalemail"": """",
    ""sl_faa33approvalon"": """",
    ""sl_faa33approval"": """",
    ""sl_faa34apprvaldone"": """",
    ""sl_faa34approvalon"": """",
    ""sl_fdabatchid"": ""ad0baa9a-8f48-4393-8a79-41a129104306"",
    ""sl_fiscalmonth"": """",
    ""sl_fiscalyear"": """",
    ""importsequencenumber"": """",
    ""sl_originaltotal_base"": """",
    ""sl_originaltotal"": """",
    ""sl_paymentcountrollup"": ""18"",
    ""sl_paymentcountrollup_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_paymentcountrollup_state"": ""1"",
    ""sl_preapprovaldone"": ""Yes"",
    ""sl_preliminaryapprovedon"": ""4/15/2021 4:57:31 PM"",
    ""processid"": """",
    ""statecode"": ""Active"",
    ""statuscode"": ""Active"",
    ""sl_subbatchdeferalreason"": ""System Outage"",
    ""timezoneruleversionnumber"": ""0"",
    ""sl_originaltotalamount"": ""49642"",
    ""sl_originaltotalamount_base"": ""49642"",
    ""sl_originaltotalamount_date"": ""5/7/2021 5:13:15 PM"",
    ""sl_originaltotalamount_state"": ""1"",
    ""utcconversiontimezonecode"": ""35"",
    ""versionnumber"": ""5796280"",
    ""transactioncurrencyid"": ""b1c907f7-1679-eb11-b1ab-0022486d7e62"",
    ""organizationid"": ""4172e8c8-b481-482b-a17b-beb6211a9163"",
    ""sl_batchfaa34approver.azureactivedirectoryobjectid"": """",
    ""createdonbehalfby.azureactivedirectoryobjectid"": """",
    ""createdby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_faa33approvalnotedby.azureactivedirectoryobjectid"": """",
    ""sl_faa34approver.azureactivedirectoryobjectid"": """",
    ""modifiedonbehalfby.azureactivedirectoryobjectid"": """",
    ""modifiedby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_preliminaryapprover.azureactivedirectoryobjectid"": """"
  },
  {
    ""stageid"": """",
    ""traversedpath"": """",
    ""sl_adjustedpaymentcount"": ""0"",
    ""sl_adjustedpaymentcount_date"": ""5/7/2021 5:13:14 PM"",
    ""sl_adjustedpaymentcount_state"": ""1"",
    ""sl_adjustedtotal_base"": ""0"",
    ""sl_adjustedtotal"": ""0"",
    ""sl_adjustedtotal_date"": ""5/7/2021 5:13:14 PM"",
    ""sl_adjustedtotal_state"": ""1"",
    ""sl_approvaldate"": """",
    ""sl_name"": ""FDA20210326"",
    ""sl_workflowstatus"": ""Workflow Ended"",
    ""sl_calrequisitionnumber"": """",
    ""sl_calresponsefilestatus"": ""Not Processed"",
    ""sl_calsubbatchstatus"": ""Defer"",
    ""sl_csgprequisitionnumber"": ""014746221010008"",
    ""sl_csgpresponsefilestatus"": ""Not Processed"",
    ""sl_cslsubbatchstatus"": ""Undefer"",
    ""sl_dlrequisitionnumber"": ""014746221010007"",
    ""sl_dlresponsefilestatus"": ""Not Processed"",
    ""exchangerate"": ""1"",
    ""sl_faa33approvalemail"": """",
    ""sl_faa33approvalon"": """",
    ""sl_faa33approval"": """",
    ""sl_faa34apprvaldone"": """",
    ""sl_faa34approvalon"": """",
    ""sl_fdabatchid"": ""23d6de7c-9805-4ce4-ae0e-1adc06f4c646"",
    ""sl_fiscalmonth"": """",
    ""sl_fiscalyear"": """",
    ""importsequencenumber"": """",
    ""sl_originaltotal_base"": """",
    ""sl_originaltotal"": """",
    ""sl_paymentcountrollup"": ""2248"",
    ""sl_paymentcountrollup_date"": ""5/7/2021 5:13:14 PM"",
    ""sl_paymentcountrollup_state"": ""1"",
    ""sl_preapprovaldone"": """",
    ""sl_preliminaryapprovedon"": ""4/19/2021 3:32:21 PM"",
    ""processid"": """",
    ""statecode"": ""Active"",
    ""statuscode"": ""Active"",
    ""sl_subbatchdeferalreason"": ""System Outage"",
    ""timezoneruleversionnumber"": ""0"",
    ""sl_originaltotalamount"": ""8524678"",
    ""sl_originaltotalamount_base"": ""8524678"",
    ""sl_originaltotalamount_date"": ""5/7/2021 5:13:14 PM"",
    ""sl_originaltotalamount_state"": ""1"",
    ""utcconversiontimezonecode"": ""35"",
    ""versionnumber"": ""5796275"",
    ""transactioncurrencyid"": ""b1c907f7-1679-eb11-b1ab-0022486d7e62"",
    ""organizationid"": ""4172e8c8-b481-482b-a17b-beb6211a9163"",
    ""sl_batchfaa34approver.azureactivedirectoryobjectid"": """",
    ""createdonbehalfby.azureactivedirectoryobjectid"": """",
    ""createdby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_faa33approvalnotedby.azureactivedirectoryobjectid"": """",
    ""sl_faa34approver.azureactivedirectoryobjectid"": """",
    ""modifiedonbehalfby.azureactivedirectoryobjectid"": """",
    ""modifiedby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_preliminaryapprover.azureactivedirectoryobjectid"": """"
  },
  {
    ""stageid"": """",
    ""traversedpath"": """",
    ""sl_adjustedpaymentcount"": ""0"",
    ""sl_adjustedpaymentcount_date"": ""5/7/2021 5:13:14 PM"",
    ""sl_adjustedpaymentcount_state"": ""1"",
    ""sl_adjustedtotal_base"": ""0"",
    ""sl_adjustedtotal"": ""0"",
    ""sl_adjustedtotal_date"": ""5/7/2021 5:13:14 PM"",
    ""sl_adjustedtotal_state"": ""1"",
    ""sl_approvaldate"": """",
    ""sl_name"": ""FDA20210413"",
    ""sl_workflowstatus"": """",
    ""sl_calrequisitionnumber"": """",
    ""sl_calresponsefilestatus"": ""Not Processed"",
    ""sl_calsubbatchstatus"": """",
    ""sl_csgprequisitionnumber"": """",
    ""sl_csgpresponsefilestatus"": ""Not Processed"",
    ""sl_cslsubbatchstatus"": """",
    ""sl_dlrequisitionnumber"": """",
    ""sl_dlresponsefilestatus"": ""Not Processed"",
    ""exchangerate"": ""1"",
    ""sl_faa33approvalemail"": """",
    ""sl_faa33approvalon"": """",
    ""sl_faa33approval"": """",
    ""sl_faa34apprvaldone"": """",
    ""sl_faa34approvalon"": """",
    ""sl_fdabatchid"": ""373bb1da-6558-4b97-b0dc-28592e975288"",
    ""sl_fiscalmonth"": """",
    ""sl_fiscalyear"": """",
    ""importsequencenumber"": """",
    ""sl_originaltotal_base"": """",
    ""sl_originaltotal"": """",
    ""sl_paymentcountrollup"": ""0"",
    ""sl_paymentcountrollup_date"": ""5/7/2021 5:13:14 PM"",
    ""sl_paymentcountrollup_state"": ""1"",
    ""sl_preapprovaldone"": """",
    ""sl_preliminaryapprovedon"": """",
    ""processid"": """",
    ""statecode"": ""Active"",
    ""statuscode"": ""Active"",
    ""sl_subbatchdeferalreason"": """",
    ""timezoneruleversionnumber"": """",
    ""sl_originaltotalamount"": ""0"",
    ""sl_originaltotalamount_base"": ""0"",
    ""sl_originaltotalamount_date"": ""5/7/2021 5:13:14 PM"",
    ""sl_originaltotalamount_state"": ""1"",
    ""utcconversiontimezonecode"": """",
    ""versionnumber"": ""5796274"",
    ""transactioncurrencyid"": ""b1c907f7-1679-eb11-b1ab-0022486d7e62"",
    ""organizationid"": ""4172e8c8-b481-482b-a17b-beb6211a9163"",
    ""sl_batchfaa34approver.azureactivedirectoryobjectid"": """",
    ""createdonbehalfby.azureactivedirectoryobjectid"": """",
    ""createdby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_faa33approvalnotedby.azureactivedirectoryobjectid"": """",
    ""sl_faa34approver.azureactivedirectoryobjectid"": """",
    ""modifiedonbehalfby.azureactivedirectoryobjectid"": """",
    ""modifiedby.azureactivedirectoryobjectid"": ""b9cb9219-a667-44db-b692-f8603b5eae29"",
    ""sl_preliminaryapprover.azureactivedirectoryobjectid"": """"
  }
]
";
        public Task<DisbursementBatch> GetDisbursementBatch()
        {
            var data = JsonSerializer.Deserialize<IEnumerable<DisbursementBatch>>(dataJson);
            return Task.FromResult(data.First());
        }
    }
}
